defines = {

-- IMPORTANT NOTE:
-- Do not add or remove new entries, only value changes are allowed.
-- Addition or removal of entries requires rebuilding the exe.

start_date = '1946.1.1',
end_date = '1991.12.31',

land_combat = 'land_doctrine_practical',
naval_combat = 'naval_doctrine_practical',
air_combat = 'air_doctrine_practical',
bombing = 'air_doctrine_practical',

base_militia = 'militia_brigade',

country = {
	CORE_LOSE 				= 50,
	CORE_GAIN 				= 5,
	YEARS_OF_NATIONALISM 	= 1,   -- Years of Nationalism
	YEARS_UNTIL_BROKEN 		= 2,    -- Years until rebel held capital results in broken country.
	REBEL_ACCEPTANCE_MONTHS = 60,
	ELECTION_RANDOMNESS 	= 0.15,
	ELECTION_MINISTER_DISSENT_PENALTY = -0.1,
	MAX_NUMBER_OF_SPIES 	= 15,
	SPY_DETECTION_CHANCE 	= 0.1,
	SPY_MISSION_CHANGE_DAYS = 7,
	SPY_CONNECTION_DETECTION_CHANCE 	 = 0.5,
	SPY_BASE_CONNECTION_DETECTION_CHANCE = 0.5,
	SPY_UNIT_DETECTION_CHANCE 		= 0.5,
	SPY_INTEL_MISSION_BONUS 		= 0.5,   -- % better when focusing on a field
	SPY_PARTY_ORGANIZATION_BOOST 	= 0.02,
	SPY_POINT_ANNUAL_GAIN = 2, 	-- annual spy points gain
	BASE_TECH_DECAY 				= -0.025,  -- how many percent lost each month in tech categories.
	MAX_TECH_ABILITY				= 50,
--	NUKE_UNITY_IMPACT	= 1.0,		removed: NU impact from being nukes.
	NUKE_DISSENT_IMPACT	= 1.0,		-- dissent impact from being nukes.
	NUKE_IMPACT_SCALE	= 0.02,		-- impact effect scale
	MOBILIZE_THREAT_IMPACT = 5.0,	-- threat from when mobilizing.
	SPY_THREAT_INCREASE_ACTION = 0.01,	-- daily threat increase from spy action
	POPULARITIY_RANDOMNESS = 5,
	PARTY_POP_CHANGE_RATE = 10, -- Inversly affects how fast party popularity gets closer to organisation
	MOBILIZATION_BONUS_DAYS = 30, -- Number of days reinforcements benefit from mobilization
	NO_MISSION_SPY_DETECTION_MULTIPLIER = 0.1, -- The risk of being detected is multiplied with this number when not performing any missions
	DEMOBILIZATION_FACTOR = 0.5, -- The amount of manpower you get back from units when demobilizing.
	NUMBER_OF_VICTORY_CONDITIONS = 15, -- The number of victory conditions each faction needs to pick.
	VICTORY_CONDITIONS_TO_WIN = 12, -- The number of victory conditions each faction needs to win.
	VALHALLA_DISSENT_RATIO = 0.01, -- This number * MP Lost from Valhalla = additional dissent
	DISSENT_NONLINEAR_OFFSET = 50, -- When the curve breaks and become LOG()
	DISSENT_NONLINEAR_VALUE = 5, -- the rate at which the effects grows until the Offset
	DISSENT_INCREASE_MAX = 0.10,  -- min and max of dissent change by social spending slider
	DISSENT_DECREASE_MAX = 0.05,
	MAX_SPY_CARDS = 5,	-- max spy cards
	SPY_CARD_COST = 5,  -- cost of 1 card
	SPY_MISSION_LENGTH = 3,	-- default spy mission length
	SPY_SKILL_ADD_CHANCE = 20, -- spy skill increase chance% on successful missions
	SPY_DEPLOYMENT_COOLDOWN = 5, -- number of days between sending spies to one country
	SPY_CARDS_COUNTRY_COOLDOWN = 30, -- number of days between sending agents to one country
	SPY_CARDS_ACTION_COOLDOWN = 1, -- number of days between each action of one agent
	GUERRILLAS_RR_DURATION = 180, -- in days
	GUERRILLAS_BASE_REBEL_DURATION = 730, -- +- estimate
	GUERRILLAS_ESTIMATE_REBEL_TIME = 365,
	SPYLEVEL_VISIBLE = -0.75,
	SPYLEVEL_NAME = 0,
	SPYLEVEL_MISSION = 0.15,
	SPYLEVEL_PROGRESS = 0.25,
	SPYLEVEL_SENDER = 0.5,
	MAXLEVEL_TECHNOLOGY = 12
},

economy = {
	CONVOY_BUILD_COST 		= 2,
	CONVOY_BUILD_TIME 		= 100,
	ESCORT_BUILD_COST 		= 4,
	ESCORT_BUILD_TIME 		= 240,
	BUILDING_REPAIR_SPEED 		= 0.1,
	THREAT_FROM_CONVOYS_MODIFIER	= 0.1,
	CONVOY_CONSTRUCTION_SIZE 	= 10,
	MAX_DAILY_TRADE			= 100,
	CONVOY_PATH_LENGTH_MULT		= 0.33,  -- Convoy path length effect on needed transports
	CONVOY_TRADE_WEIGHT_MULT	= 0.2,	 -- Trade route convoy effect on needed transports
	OWNED_PROVINCE_REPAIR = 0.1, -- scale for owned province repairs
	CONTROLLED_PROVINCE_REPAIR = 0.1, -- scale for non-owned province repairs
	MP_MONEY_COST = 0.01, -- cost in money of 1MP in unit
	EQP_MONEY_COST = 0.01,
	TECHCOST_A = 1.00,
	TECHCOST_B = 1.00,
	TECHCOST_PERCENT = 0.05,
 	RESEARCH_STEP_BELOW_AVERAGE = 0.5,
 	RESEARCH_STEP_NORMAL = 1.0,
 	RESEARCH_STEP_ABOVE_AVERAGE = 1.15,
 	RESEARCH_STEP_FAST = 1.3,
	RESEARCH_COST_CAP = -0.9,			-- max research cost reduction 90%
	RESEARCH_TIME_CAP = -0.9,			-- max research time reduction 90%
	SPIES_DAILY = 0.01,
	MONEY_SUPPLY_COST = 0.01,
	CONVOY_LEASING_COST = 0.01,			-- default convoy leasing cost 
	GLOBAL_TRANSPORT_CAPACITY = 5000,		-- starting global ship count of global cargo companies 
	FACTORIES_PER_REGION = 6,
	FUEL_DECAY = 0.15,					-- a factor to scale value of good lost every day, when above the limit
	URANIUM_DECAY = 0.15,
	SPIES_DECAY = 0.15,
	FUEL_STOCKPILE_FACTOR = 200,			-- factor to scale each good's limit value (unused yet)
	URANIUM_STOCKPILE_FACTOR = 500,
	SPIES_STOCKPILE_FACTOR = 500,
	UNITS_GOODS_USAGE = 30,               -- days of usage for fuel and supplies, used for min stock
	MAX_STOCK_FUEL_FACTOR = 1,		  -- used to set max stock
	MAX_STOCK_SUPPLIES_FACTOR = 2,
	STOCK_DECAY_ABOVE_LIMIT = 0.1,		  -- percantage value of decay if current stock > limit
	UPKEEP_COST = 0.001,				  -- percentage value of normal decay 
	MARKET_TRANSACTIONS_FACTOR = 0.01,     -- percentage value of bought/sold good if below/above wanted stock each day
	DEFAULT_DI_VALUE = 0.5,
	SERVICES_INCOME_SCALE = 1.00,
	DEFAULT_TAX_PCT = 30,
	DI_SCALE = 10000, -- 0..1 * SCALE = DI 
	TAX_DI_EFFECT = 0.01,			-- 1% tax change effect to DI
	PROVINCE_UPKEEP_FACTOR = 0.01,
	CONSUMPTION_FACTOR = 0.8,
	IMPORT_PRICE_FACTOR = 1,
	INFRA_BUDGET = 30,			-- % of GDP for max infra slider setting
	INFRA_DAMAGE_TIME = 365, -- number of days, after which infra will drop by percent value set by Needed - Budget ( if Needed > Budget, so we dont pay upkeep cost )
	DVI_BASE_TIME = 10,
	DVI_UPDATE_DAYS = 365,
	ECONOMYAI_MONEY_LIMIT = 200,	-- only spend money above this sum by economy AI
	PRICE_TWEAKER_WORKFORCE = 0.02,
	LOCAL_SUPPLY_PRICE_FACTOR = 0.6,		-- produced local supplies price factor from world market
	WORKERS_MIGRATION_RATE = 0.01, -- how many people can daily change job
	POP_DEATH_RATE = 0.001,
	POP_TIMEBASE = 0.0833, -- 1/12
	POP_NSTEPSIZE = -5,
	POP_BABY = 0.0501,
	POP_MAX_AGE = 85
},

military = {
	POPULATION_MANPOWER = 0.42,   -- factor to set manpower number basing on pop group
	MAX_MANPOWER = 15,
	HISTORICAL_MODEL_MAX = 12, 	-- (10) historical models max
	HISTORICAL_AIR_MODEL_MAX = 5, 	-- historical models max
	HISTORICAL_LAND_MODEL_MAX = 5, 	-- historical models max
	HISTORICAL_NAVY_MODEL_MAX = 12, 	-- historical models max
	BASE_CHANCE_TO_AVOID_HIT = 0.8,	-- Base chance to avoid hit if defences left.
	CHANCE_TO_AVOID_HIT_AT_NO_DEF = 0.6,	-- chance to avoid hit if no defences left.
	RIVER_CROSSING_PENALTY = 0,	-- (-0.5) base river crossing penalty.
	AMPHIBIOUS_LANDING_PENALTY = -0.6,	-- amphibious landing penalty
	PARADROP_PENALTY = -0.5,	-- paradrop penalty
	MULTIPLE_COMBATS_PENALTY = 0.5,	-- multiple combat modifier
	ENVELOPMENT_PENALTY = 0.1,	-- envelopment penalty, for each direction.
	ENCIRCLED_PENALTY = 0.1,	-- for completely encircled units.
	DIG_IN_FACTOR = 0.02,	-- dig-in factor.
	COMBAT_SUPPLY_LACK_IMPACT = 0.5,	--combat penalty factor on lack of supplies.
	COMBAT_DISSENT_IMPACT = 0.33,	-- dissent modifier in combat.
	PRIDE_SUNK_DISSENT_IMPACT = 2,	-- Pride of the Fleet Sunk impact
	COMBINED_ARMS_BONUS = 0.2,	--combined arms
	SUPPLY_TAX = 0.1,	-- supplies cost for moving through a province.
	SUPPLYPOOL_DAYS = 7,	-- days of supply.
	SUPPLY_SAME_AREA_DIST_CUTOFF = 10, -- No convoys to within this many provinces from the main supplier province
	PARASUPPLYPOOL_DAYS = 7, -- when paradropped
	RADAR_RANGE = 0.18,
	BASE_RADIO_STRENGTH = 10,
	EXP_GAIN_LAND = 0.30, --(15)
	EXP_GAIN_NAVAL = 2.0, --(4)
	EXP_GAIN_AIR = 1.5, --(0.2)
	EXP_GAIN_DIV = 1.5,
	EXP_GAIN_LEADER = 200.0,
	PRIDE_BONUS_EXP = 10,
	PRIDE_BASE_REDESIGNATION_DISSENT = 1,
	LAND_SPEED_MODIFIER = 0.05,
	NAVAL_SPEED_MODIFIER = 0.5,
	AIR_SPEED_MODIFIER = 0.3,	
	MINIMUM_STRENGTH = 50,		--minimum strength of a land division at production.  50 = 5000 men.
	BRIGADES_IN_DIVISION = 5,	--number of allowed brigades in a division.
	MINIMUM_DEPLOY = 0.25,   --value of production progress, below which pre-deployment is impossible
	COMBAT_LEADER_IMPACT = 0.05,	
	COMBAT_MOVEMENT_SPEED = 0.33, -- Reduced from 0.5	
	COMBAT_PUSHBACK_DAMAGE = 1.0,	
	COMBAT_PUSHBACK_CHANCE_FOR_DAMAGE = 50,	-- 10 = 10%
	UNIT_ATTACK_DELAY = 168,
	UNIT_ATTACK_DELAY_MODIFY = 10,
	PARATROOP_MISSION_DELAY = 168, 	-- Paratroops cannot make another attack drop before this many hours
	PARATROOP_DROP_ORG_MULT = 0.66, -- Paratroop org is multiplied with this after they have landed (and combat is over)
	PARATROOP_MISSION_ORG_REQ = 0.95, -- Paratroop brigades need at least this percent of max org to perform drops
	UNIT_DIGIN_CAP = 10,
	BOMB_STRATEGIC_RESOURCES = 0.1,
	BOMB_STRATEGIC_PRODUCTION = 0.005,
	BOMB_STRATEGIC_BUILDINGS = 0.005,
	OFFICER_COMBAT_LOSS = 0.007,
	AGGRESSIVE_ORGANISATION_LIMIT = 0.05,
	DEFENSIVE_ORGANISATION_LIMIT = 0.3,
	PASSIVE_ORGANISATION_LIMIT = 0.6,
	AGGRESSIVE_STRENGTH_LIMIT = 0.05,
	DEFENSIVE_STRENGTH_LIMIT = 0.3,	
	PASSIVE_STRENGTH_LIMIT = 0.6,
	LAND_COMBAT_THREAT_IMPACT = 0.12,
	NAVAL_COMBAT_THREAT_IMPACT = 0.25,
	AIR_COMBAT_THREAT_IMPACT = 0.01,
	BOMBING_THREAT_IMPACT = 0.15,
	LAND_DOCTRINE_INCREASE = 0.001,
	NAVAL_DOCTRINE_INCREASE = 0.01,
	AIR_DOCTRINE_INCREASE = 0.01,
	BOMBING_DOCTRINE_INCREASE = 0.01,
	MOMENTUM_BATTLES_WON = 10,
	MOMENTUM_EFFECT_DAYS = 30,	
	MORALE_SCALE0 = 90,
	MORALE_SCALE1 = 1,
	MORALE_SCALE2 = 0.5,
	MORALE_SCALE3 = 10,
	MORALE_SCALE4 = 5,
	INTERBRANCH_SCALE1 = 0.1,
	SUPPLYSTOCK_REPLENISH_RATE = 2.0,
	MAX_UNIT_SUPPLY_STOCK = 5.0, 
	MILITIA_DRAFT_NATIONAL_UNITY_LOST = -2,
	MILITIA_DRAFT_SUPPLY_COST = -3000.0,
	MILITIA_DRAFT_MIN_MP = 30,
	MILITIA_POP_PER_UNIT = 20000,
	MILITIA_MAX_UNITS_FACTOR = 10,
	GUERRILLA_SUPPORT_MONEY_COST = -500,  -- cost of supporting 1 Guerrilla unit
	REVOLT_CHANCE_RR_DIVISOR = 40000,  -- determines the chance of revolt popping up
	REVOLT_CHANCE_DIVISOR = 730,		-- NOT USED! 
	REVOLT_CHECKING_DISTANCE = 300,             -- radious to check neighbouring provinces [km]
	OFFENSIVE_SUPPLY_RATE = 3,
	OFFENSIVE_FUEL_RATE = 3,
	EQP_LOSS_SCALE = 0.02,
	MP_LOSS_SCALE = 0.8,
	ORG_LOSS_SCALE = 0.8,
	AIR_INTELLIGENCE_EFFICIENCY = 0.05,
	MOMENTUM_INACTIVITY_DAYS = 30,
	LAND_DIMISHING_RETURN = 0.01,
	COMBAT_DIFFICULTY_IMPACT = 0.2,
	BASE_COMBAT_WIDTH = 10,
	ADDITIONAL_COMBAT_WIDTH = 5,
	RETREAT_PROGRESS = 0.9,
	BASE_NIGHT_PENALTY = -0.4, --(0.5) Night time penalty
	BASE_FORT_PENALTY = -0.10, --(0.09)
	BASE_STACKING_PENALTY = -0.04, --(-0.1)
	RADAR_COMBAT_IMPACT = 0.05,
	COMBAT_EVENT_DURATION = 10, --Increased by 2 to give longer duration
	STRAT_RAIDER_FOUGHT_IMPACT = 0.015,
	STRAT_BOMBER_FOUGHT_IMPACT = 0.1,
	STRAT_AIR_RAIDER_FOUGHT_IMPACT = 0.02,
	STRAT_NO_ALLIES_HELP_PENALTY = -0.001,
	STRAT_ALLIES_HELP = 0.1,
	STRAT_BOMBING_PENALTY = -0.05,
	STRAT_CONVOY_DAMAGE = -0.5,
	LAND_COMBAT_ORG_DICE_SIZE = 2, --(3)
	LAND_COMBAT_STR_DICE_SIZE = 3, -- (2)
	LAND_COMBAT_STR_ARMOR_ON_SOFT_DICE_SIZE = 2,
	LAND_COMBAT_ORG_ARMOR_ON_SOFT_DICE_SIZE = 5,
	LAND_COMBAT_STR_DAMAGE_MODIFIER = 0.012,  -- (0.12) Strength Damage modifier 
	LAND_COMBAT_ORG_DAMAGE_MODIFIER = 0.10,   -- (1.0) Organization Damage modifier
	AIR_COMBAT_ORG_DICE_SIZE = 9,
	AIR_COMBAT_STR_DICE_SIZE = 4,
	AIR_COMBAT_CRITICAL_HIT_DAMAGE_MUL = 10,
	AIR_COMBAT_CRITICAL_HIT_DAMAGE_CHANCE = 10,
	AIR_COMBAT_ORG_DAMAGE_MODIFIER = 0.3,
	AIR_COMBAT_STR_DAMAGE_MODIFIER = 0.2,
	AIR_COMBAT_NAV_SURPRISE_CHANCE = 25, -- Chance of attacking naval bombers getting a surprise bonus (%)
	AIR_COMBAT_NAV_SURPRISE_BONUS = 0.75, -- Naval bomber surprise attack bonus
	AIR_COMBAT_NAV_SURPRISE_ROUNDS = 3, -- Combat rounds that the naval bomber surprise chance lasts
	AIR_COMBAT_CAG_ORG_DAMAGE_MOD = 0.75, -- ORG damage to CAGs is multiplied by this
	AIR_COMBAT_CAG_STR_DAMAGE_MOD = 0.75, -- STR damage to CAGs is multiplied by this
	NAVAL_COMBAT_ORG_DICE_SIZE = 8,
	NAVAL_COMBAT_STR_DICE_SIZE = 3,
	NAVAL_COMBAT_CRITICAL_HIT_DAMAGE_MUL = 10,
	NAVAL_COMBAT_CRITICAL_HIT_DAMAGE_CHANCE = 10,
	NAVAL_COMBAT_ORG_DAMAGE_MODIFIER = 0.1,
	NAVAL_COMBAT_STR_DAMAGE_MODIFIER = 0.1,
	NAVAL_COMBAT_SUB_SURPRISE_CHANCE = 25, -- Chance of attacking subs getting a surprise bonus (%)
	NAVAL_COMBAT_SUB_SURPRISE_BONUS = 5.0, -- Sub surprise attack bonus
	NAVAL_COMBAT_SUB_SURPRISE_ROUNDS = 3, -- Combat rounds that the sub surprise chance lasts
	AIR_COMBAT_ON_BOMBING = -0.1,
	BASE_PROXIMITY_BONUS = 0.1,
	INTERCEPT_ATTACK_BONUS = 0.2,
	AIR_SUP_DEFEND_BONUS = 0.2,
	SHORE_BOMBARDMENT_MOD = -0.001,
	SHORE_BOMBARDMENT_CAP = -0.25,
	AIR_STACKING_PENALTY = -0.10,
	NAVAL_STACKING_PENALTY = -0.02,			-- OBSOLETE
	NAVAL_STACK_POS_HULL_LIMIT = 12,		-- Total Hull size up to this is fine before taking stacking penalty
	NAVAL_STACK_POS_PENALTY_HULL_MULT = 0.04, 	-- Every hull point above the limit gives this positioning penalty
	STRAT_REDEP_BASE_SPEED = 20,
	STRAT_REDEP_SUPPLY_MOD = 2.0,
	STRAT_REDEP_ORG_LOSS = 0.02,
	AIR_RANK_1 = 4,
	AIR_RANK_2 = 8,
	AIR_RANK_3 = 12,
	AIR_RANK_4 = 16,
	NAVAL_RANK_1 = 6,
	NAVAL_RANK_2 = 12,
	NAVAL_RANK_3 = 18,
	NAVAL_RANK_4 = 30,
	RADIO_CORPS_LEADER_DISTANCE = 100,
	RADIO_ARMY_LEADER_DISTANCE = 200,
	RADIO_ARMYGROUP_LEADER_DISTANCE = 300,
	RADIO_THEATHRE_LEADER_DISTANCE = 1000,
	OWNED_AND_CONTROLLED_THROUGHPUT_CAP_BONUS = 2,
	INFRA_THROUGHPUT_IMPACT = 0.5,
	SURPRISE_BONUS = 0.33,
	AIR_SUPPLY_FACTOR = 0.5,
	UNIT_UPGRADE_COST = 0.5,
	UNIT_UPGRADE_TIME = 0.3, --(0.7)
	MAX_OFFICERS = 1.4, -- officer ratio max for bonus
	LOW_ORG_REGAIN_BONUS = 0.25,
	INITIAL_UNIT_MANPOWER_STRENGTH = 1.0, -- % of unit manpower at start
	WALHALLA_DAMAGE_SCALE = 0.9, -- total damage got when in valhalla mode is multiplied by this value
	SURV_INTEL_HOURS = 4, -- Air Surveillance Mission Intel data lifetime in hours
	PARTISAN_BASED_ATTRITION = 1, -- attrition for 100% activity
	BUILDING_REDEPLOYMENT_TIME = 1, -- redeployment time in days
	UNIT_BACKTOPOOL_TIME = 30, -- unit availability time in days after moving back to pool
	AWACS_BONUS = 5, -- % bonus on AWACS/intel level
	SILO_RELOADING_TIME = 2,
	GREATBATTLE_MP = 10,	-- store battle to history if loss above 1000 men
	GREATBATTLE_EQ = 20,	-- store battle to history if equipment loss cost above 2000 $
	SUPPLYTRANSPORT_MININFRA = 0.0,
	UNIT_MANPOWER_REPLENISH = 0.05, ---5% of needed manpower replenished
	EXP_NAVAL_FORCE_MAX_HULL = 1.5, -- ships above this hull level cant sent as exp forces
	MOTHBALL_AIR_ORG = 2,	-- org value for mothballed air units
	MOTHBALL_NAVY_ORG = 1, -- org value for mothballed naval units
	MOTHBALL_UPKEEP = 0.2,	-- upkeep modifier for mothballed units
	MOTHBALL_SUPPLY = 0.1,	-- supply modifier for mothballed units
	NAVAL_BASE_LOG_FACTOR = 8  -- port logistics throughput factor
},

diplomacy = {
	WARDEC_BELIGERENCY = 50.0, 
	WARDEC_WAR_DIPLOMACY_HIT = 100.0,
	WARDEC_DIPLO_COST = 5.0,
	JOIN_ALLIANCE_DIPLO_COST = 5.0,
	LEAVE_ALLIANCE_DIPLO_COST = 1.0,
	GUARANTEE_DIPLO_COST = 5.0,
	REVOKE_GUARANTEE_DIPLO_COST = 1.0,
	CALLALLY_DIPLO_COST = 5.0,
	NAP_INFLUENCE_COST = 5.0,
	PURCHASE_INFLUENCE_COST = 0.0,
	EMBARGO_DIPLO_COST = 3.0,
	MILACCESS_DIPLO_COST = 1.0,
	INFLUENCE_DIPLO_COST = 3.0,
	RELATION_INFLUENCE_COST = 1.0,
	JOINBLOCK_INFLUENCE_COST = 5.0,	
	ALLIANCE_NEUTRALITY_LIMIT = 25.0,
	ALLIANCE_RELATION_CHANGE = 50.0,
	ALLIANCE_REJECT_RELATION_CHANGE = -50.0,
	GUARANTEE_NEUTRALITY_LIMIT = 60.0,
	NAP_RELATION_CHANGE = 25.0,
	LEAVE_NAP_RELATION_CHANGE = -30.0,
	NAP_JOIN_DIPLO_COST = 2.0,
	NAP_REJECT_RELATION_CHANGE = -25.0,
	LEAVE_NAP_DIPLO_COST = 1.0,
	LEAVE_NAP_THREAT_COST = 5.0,
	MILACC_ACCEPT_RELATION_CHANGE = 25,
	MILACC_DECLINE_RELATION_CHANGE = -30,
	MILACC_CANCEL_RELATION_CHANGE = -20,
	REVOKE_GUARANTEE_RELATION_CHANGE = -20,
	DAYS_OF_INFLUENCE_RELATION_CHANGE = -1,
	DAYS_OF_ALIGN_RELATION_CHANGE = -1,
	ALIGN_DIPLO_COST = 1.0,
	EMBARGO_RELATION_CHANGE = -50.0,
	EMBARGO_NETRALITY = 30.0,
	EMBARGO_THREAT_COST = 5.0,
	JOIN_FACTION_DIPLO_COST = 1.0,
	INVITE_FACTION_DIPLO_COST = 3.0,
	JOIN_FACTION_NEUTRALITY = 25.0,
	INVITE_FACTION_NEUTRALITY = 25.0,
	TRADE_RELATION_CHANGES = 20.0,
	TRADE_DIPLO_COST = 3.0,
	TRADE_CANCEL_DIPLO_COST = 1.0,
	TRADE_CANCEL_RELATION_COST = 15.0,
	EXPEDITION_DIPLO_COST = 1.0,
	EXPEDITION_RETURN_TIME = 30.0,
	EXPEDITION_RECLAIM_TIME = 30.0,
	LICENCE_DIPLO_COST = 1.0,
	ALLOW_DEBT_DIPLO_COST = 1.0, 
	REVOKE_DEBT_DIPLO_COST = 1.0,
	YEARS_TO_REPAY_DEBT = 50.0,
	INFLUENCE_UPKEEP = 0.02,
	REGULAR_CONSTRUCTION_THREAT_IMPACT = 0.5,
	NEUT_INCREASE_DIFF_CONTINENT = 10,
	NEUT_REDUCTION_AT_CLAIMS = 20,
	SHARE_TECH_INFLUENCE_COST = 1.0,
	NAP_EXPIRY_MONTHS = 45,				-- NAPs expire after this many months
	NAP_UNBREAKABLE_MONTHS = 6,			-- NAPS cannot be broken for this many months
	NAP_FORCE_BALANCE_RULE_MONTHS = 6,		-- The NAP border force balance rule changes with this interval
	NAP_BREAK_FORCE_BALANCE_1 = 2.0,		-- 2-1 brigades along the border required to break NAP
	NAP_BREAK_FORCE_BALANCE_2 = 1.0,		-- 1-1 brigades along the border required to break NAP
	NAP_BREAK_FORCE_BALANCE_3 = 0.5,		-- 1-2 brigades along the border required to break NAP
	SUPPORT_PARTY_PCT = 2,				-- Support party popularity in percentage
	SUPPORT_PARTY_DISSENT = 1,			-- Causes x% dissent on party support
	SUPPORT_PARTY_LIMIT = 5,			-- Defines % of dissent above party support is disabled
	PEACE_INFAMY_PROVINCE = 1.0,		-- Infamy value per province
	PEACEGOAL_ANNEX = 100,				-- Peacegoal: Annex
	PEACEGOAL_PUPPET = 85,				-- Peacegoal: Puppet
	PEACEGOAL_HUMILIATE = 20,			-- Peacegoal: Humiliate
	PEACEGOAL_DISARM = 50,				-- Peacegoal: Forced Disarmament
	PEACEGOAL_MIL_ACCESS = 8,			-- Peacegoal: Forced Military Access
	MAJOR_NATIONS = 12,					-- the number of MAJOR nations
	BASE_CHANCE_SPY_MISSION = 0.20,
	DIPLOMATIC_VOTING_SCALE = 0.50,
	NEUTRALITY_CHANCE_ACCESS = 50.0,	-- neutrality requirements
	NEUTRALITY_CHANCE_DOW = 50.0,
	NEUTRALITY_CHANCE_DEFENSIVE_WAR = 75.0,
	YEARLY_DIPLO_POINT = 15.0,			-- yearly diplo point generation
	PRESTIGE_POINT_SCALE = 1.0,			-- yearly prestige point generation
	NEGOTIATION_UNIT_MULTIPLIER = 1.5,	-- unit cost multiplier at negotiation
	VOTE_YES_NO_COST = 1,				-- voting yes/no action cost
	VOTE_ABSTAIN_COST = 0,				-- voting abstain cost
	VOTE_VETO_COST = 10,				-- voting veto cost
	TRUCE_DURATION = 1095,				-- truce duration
	INHERIT_URANIUM = 1 				-- modifier of uranium inherited from annex
},

alignment = {
	ALIGNMENT_INTERVAL = 30,
	RELATION_WEIGHT = 0.003,
	IDEOLOGY_WEIGHT = 1.00,
	PROXIMITY_WEIGHT = 0.4,
	REVANCHISM_WEIGHT = 0.1,
	THREAT_WEIGHT = 0.15,
	REPULSION_WEIGHT = 0.01,
	FACTION_JOIN_DIST = 35.0,
	WAR_THREAT = 35.0,
	LARGE_COUNTRY_IC = 300.0, -- used to scale threat impact with country IC
	REPULSION_IC_FACTOR = 8	-- If a country is of another ideology, the repulsion factor is modified by this value times its max IC, divided by the faction IC
},

map = {
	SUEZ = 5632,
	SUEZ_BLOCKER = 7515,
	PANAMA = 7703,
	PANAMA_BLOCKER = 2061,
	GIBRALTAR = 3758,
	GIBRALTAR_BLOCKER = 4575,
	MALACCA = 14611,
	MALACCA_BLOCKER = 12020,	
	BLACKSEA = 5906,
	BLACKSEA_BLOCKER = 14924,
	AZOV = 17058,
	AZOV_BLOCKER = 8050,	
	BABELMANDEB = 14836,
	BABELMANDEB_BLOCKER = 8487,
	DANISH = 16445,
	DANISH_BLOCKER = 5488,
	DANISH_CHANNEL = 14830,
	DANISH_CHANNEL_BLOCKER = 5413,
	KIEL_CANAL = 14905,
	KIEL_CANAL_BLOCKER = 5416,
	MAGELLAN = 16128,
	MAGELLAN_BLOCKER = 2692,
	TSUGARU = 17731,
	TSUGARU_BLOCKER = 14237,
	TARTARY = 8626,
	TARTARY_BLOCKER = 14230,
	QIONGZHOU = 13269,
	QIONGZHOU_BLOCKER = 12473,
	SUNDA = 13211,
	SUNDA_BLOCKER = 12232,
	FOVEAUX = 18091,
	FOVEAUX_BLOCKER = 14824,
--Deactivated straits	
	--HORMUZ = 9412,
	--HORMUZ_BLOCKER = 9313,
	--TAIWAN = 17597,
	--TAIWAN_BLOCKER = 13125,
	--FLORIDA = 16025,
	--FLORIDA_BLOCKER = 2028,
	--DOVER = 14917,
	--DOVER_BLOCKER = 4904,
	--MAKASSAR = 17605,
	--MAKASSAR_BLOCKER = 13004,
	--BALTIC = 17003,
	--BALTIC_BLOCKER = 6672	
},


weather = {
	PRESSUREMIN 			= 840,	                           
	PRESSUREMAX 			= 1090,                                   
	PRESSUREDEFAULT 		= 960,                                   
	PRESSURESTEP			= 1,                                      
	PRESSUREREDUCTION		= 1,                                      
	PRESSUREPROPAGATION 	= 10,                                     
	PRESSURETHRESHOLD 		= 300,                                    
	MAXHUMIDITY 			= 100,                                    
	MINHUMIDITY 			= 0,                                      
	MAXFROMEACHPRESSURE 	= 8,                                      
	HIGHTEMPERATUREATTRITIONTHRESHOLD 	= 30,		     
	LOWTEMPERATUREATTRITIONTHRESHOLD 	= -4,    
	WINDATTRITIONTHRESHOLD 				= 30,     
	CLOUDCOVERAGETEMPERATUREDROP 		= -3,      
	LANDRAINIMPACTMODIFIER				= 0.05, 
	LANDRAINIMPACTCAP 					= 0.90,   
	LANDLOWTEMPERATURETHRESHOLD 		= -2,		-- Land battle modifier for low temperature     
	LANDLOWTEMPERATUREIMPACT			= 1.50,    
	LANDHIGHTEMPERATURETHRESHOLD 		= 30,		-- Land battle modifier for high temperature     
	LANDHIGHTEMPERATUREIMPACT 			= 0.25,    
	AIRLOWTEMPERATURETHRESHOLD 			= -5,     
	AIRLOWTEMPERATUREIMPACT 			= 0.2,    
	AIRHIGHTEMPERATURETHRESHOLD 		= 30,   
	AIRHIGHTEMPERATUREIMPACT 			= 0.2,  
	AIRWINDSPEEDMODIFIER 				= 0.025,
	AIRCLOUDMODIFIER 					= 0.25, 
	AIRRAINMODIFIER 					= 0.05, 
	BOMBLOWTEMPERATURETHRESHOLD 		= -5,   
	BOMBLOWTEMPERATUREIMPACT 			= 0.2,  
	BOMBHIGHTEMPERATURETHRESHOLD 		= 30,   
	BOMBHIGHTEMPERATUREIMPACT 			= 0.2,  
	BOMBWINDSPEEDMODIFIER 				= 0.025,
	BOMBCLOUDMODIFIER 					= 0.30,  
	BOMBRAINMODIFIER 					= 0.20,  
	NAVALWINDSPEEDMODIFIER 				= 0.001,  
	NAVALRAINMODIFIER 					= 0.33,  
	MUDDYNESSMOVEMENTMODIFIER 			= -0.75, 
	COLDMOVEMENTMODIFIER				= -0.5,
	HOURLYFROZENINCREASE 				= 0.013,  
	HOURLYTHAW 							= 0.013,  
	TEMPERATURECHANGESPEED 				= 0.06,   
	WEATHERMOVEMENTDELAY 				= 3,     
	LOWPRESSUREBASE 					= 25,   
	LOWPRESSUREOFFSET 					= 100,   
	ALLOWEDTOFLYTHRESHOLD 				= 0.8,   
	SPOTTINGCLOUDMODIFIER 				= 0.3,   
	SPOTTINGRAINMODIFIER 				= 0.3,   
	MUDDYNESSSUPPLYTAXMODIFIER			= 0.25,  
	FIRINGRANGEMODIFIER					= -0.5,
	GFX_RAINIMPACT_LIMIT				= 0.1,
	GFX_RAIN_LIMIT						= 0.1,
	GFX_SNOW_LIMIT						= 0.1,
	GFX_STORM_LIMIT						= 15.0,
	GFX_SNOW_STORM_LIMIT				= 15.0,
	GFX_PARTIAL_CLOUD_LIMIT				= 0.3,
	GFX_CLOUD_LIMIT						= 0.8
},

goods_cost = {
	SUPPLIES 		= 0.25,
	FUEL 			= 0.75,
	MONEY 			= 0.0,
	CRUDE_OIL 		= 0.75,
	METAL 			= 0.1,
	ENERGY 			= 0.05,
	RARE_MATERIALS 	= 0.2
},

}
